server:
  port: 8191
  servlet:
    context-path: /web-market-product
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 700000000
    user:
      expire-time: 100
      name: "Cart"
other:
  cache:
    cart: "Cart"
  kafka:
    consumer:
      group-id: 1
    bootstrap-servers: localhost:9092
    topic: "order_topic"